### ISSUE TITLE
What is rate and how to use it?

### ISSUE THREAD

**Issue by askfriends** [wkentaro/video-cli#3]
I am testing this module and it works fine but i am confused at "rate".
So what is rate and it is in seconds or minutes?

If i want to take a screenshot after every five minutes, what should i use?

Thanks in advance.

**Comment by wkentaro** [comment]
Which script are you talking about? video-toimg? If so, rate means frame per second (fps).

**Comment by askfriends** [comment]
> Which script are you talking about? video-toimg? If so, rate means frame per second (fps).

Yes i am talking about video-toimg, how does rate/fps affect output?
sorry for noob question but it will help me ti understand this fully.
if i set higher value like say 100, it will produce large number of screenshots in output?

**Comment by wkentaro** [comment]
Ah, sorry, it was frequency of saving instead of fps. So if you set 1, it saves the maximum number of images. If you set larger number, it saves less frequently.
